name: Manual CI

on:
  workflow_dispatch:
    inputs:
      semver:
        description: '版本号 例如 4.0.0'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build unlocker tgz
        run: |
          ls -la
          python3 esxi-build.py
          ls -la *.tgz

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.semver }}
          name: Release ${{ github.event.inputs.semver }}
          draft: true
          prerelease: false
          files: |
            *.tgz
